name: Fehlermeldung
description: Melden Sie einen Fehler.
title: "[Fehler]: "
labels: ["fehler", "triage"]
projects: ["octo-org/1", "octo-org/44"]
assignees:
  - Jacques-Mock-Schindler
body:
  - type: markdown
    attributes:
      value: |
        Danke, dass Sie sich die Zeit nehmen, einen Fehler zu melden.
  - type: checkboxes
    id: error_type
    attributes:
      label: Welche Art Fehler möchten Sie melden?
      options:
        - label: Tippfehler
        - label: Unversständliche Formulierung
        - label: Beispielcode funktioniert nicht   
    validations:
        required: false     
  - type: textarea
    id: where
    attributes:
      label: Beschreiben Sie bitte den Fehler
      description: Halten Sie sich bitte an die folgende Checkliste.
      description: Halten Sie sich bitte an die folgende Checkliste.
      placeholder: Kopieren Sie bitte die Adresse der Seite in dieses Feld.
      value: "[ ] genaue Angabe, wo sich der Fehler befindet
      
              [ ] genaue Beschreibung des Fehlers"
    validations:
      required: true
  - type: input
    id: contact
    attributes:
      label: Kontaktangaben
      description: Wie kann ich Sie erreichen, wenn ich zusätzliche 
                   Informationen brauche?
      placeholder: ex. email@example.com
    validations:
      required: false