name: Fehlermeldung
description: Melden Sie einen Fehler.
title: "[Fehler]: "
labels: ["fehler", "triage"]
projects: ["octo-org/1", "octo-org/44"]
assignees:
  - Jacques-Mock-Schindler
body:
  - type: markdown
    attributes:
      value: |
        Danke, dass Sie sich die Zeit nehmen, einen Fehler zu melden.
  - type: dropdown
    id: error_type
    attributes:
      label: Welche Art Fehler möchten Sie melden?
      options:
        - Tippfehler
        - Unversständliche Formulierung
        - Beispielcode funktioniert nicht   
      validations:
        required: false     
  - type: textarea
    id: where
    attributes:
      label: Beschreiben Sie bitte den Fehler
      description: Ersetzen Sie im folgenden Textfeld die Vorlage durch
                   Ihre Angaben.
      placeholder: Kopieren Sie bitte die Adresse der Seite in dieses Feld.
      value: "Adresse der Seite: Beschreibung des Fehlers."
    validations:
      required: true
  - type: input
    id: contact
    attributes:
      label: Kontaktangaben
      description: Wie kann ich Sie erreichen, wenn ich zusätzliche 
                   Informationen brauche?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 1.0.2 (Default)
        - 1.0.3 (Edge)
      default: 0
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com). 
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
