name: Fehlermeldung
description: Melden Sie einen Fehler.
title: "[Fehler]: "
labels: ["fehler", "triage"]
projects: ["octo-org/1", "octo-org/44"]
assignees:
  - Jacques-Mock-Schindler
body:
  - type: markdown
    attributes:
      value: |
        Danke, dass Sie sich die Zeit nehmen, einen Fehler zu melden.
  - type: dropdown
    id: error_type
    options:
      - Tippfehler
      - Unversständliche Formulierung
      - Beispielcode funktioniert nicht        
  - type: textarea
    id: where
    attributes:
      label: Beschreiben Sie bitte den Fehler
      description: Ersetzen Sie im folgenden Textfeld die Vorlage durch
                   Ihre Angaben.
      placeholder: Kopieren Sie bitte die Adresse der Seite in dieses Feld.
      value: "Adresse der Seite: Beschreibung des Fehlers."
    validations:
      required: true
  - type: input
    id: contact
    attributes:
      label: Kontaktangaben
      description: Wie kann ich Sie erreichen, wenn ich zusätzliche 
                   Informationen brauche?
      placeholder: ex. email@example.com
    validations:
      required: false
